"""Initial MVP schema.

Revision ID: 0001_initial_mvp_schema
Revises: None
Create Date: 2026-07-16

"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "0001_initial_mvp_schema"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # gen_random_uuid() is used by every UUID primary key in this revision.
    op.execute("CREATE EXTENSION IF NOT EXISTS pgcrypto")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("id", sa.UUID(), server_default=sa.text("(gen_random_uuid())"), nullable=False),
        sa.Column("username", sa.Text(), nullable=False),
        sa.Column("display_name", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("username"),
    )
    op.create_table(
        "projects",
        sa.Column("id", sa.UUID(), server_default=sa.text("(gen_random_uuid())"), nullable=False),
        sa.Column("owner_id", sa.UUID(), nullable=True),
        sa.Column("slug", sa.Text(), nullable=False),
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column("genre", sa.Text(), nullable=True),
        sa.Column("target_platform", sa.Text(), nullable=True),
        sa.Column("status", sa.Text(), server_default=sa.text("'draft'"), nullable=False),
        sa.Column("workspace_root", sa.Text(), nullable=False),
        sa.Column("current_workflow_id", sa.UUID(), nullable=True),
        sa.Column(
            "metadata",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("('{}'::jsonb)"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["owner_id"], ["users.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("slug"),
    )
    op.create_index(
        "idx_projects_metadata_gin", "projects", ["metadata"], unique=False, postgresql_using="gin"
    )
    op.create_index("idx_projects_owner_id", "projects", ["owner_id"], unique=False)
    op.create_index("idx_projects_status", "projects", ["status"], unique=False)
    op.create_table(
        "chapters",
        sa.Column("id", sa.UUID(), server_default=sa.text("(gen_random_uuid())"), nullable=False),
        sa.Column("project_id", sa.UUID(), nullable=False),
        sa.Column("chapter_number", sa.Integer(), nullable=False),
        sa.Column("title", sa.Text(), nullable=True),
        sa.Column(
            "status", sa.Text(), server_default=sa.text("'OUTLINE_DISCUSSION'"), nullable=False
        ),
        sa.Column("current_outline_document_id", sa.UUID(), nullable=True),
        sa.Column("current_draft_document_id", sa.UUID(), nullable=True),
        sa.Column("final_document_id", sa.UUID(), nullable=True),
        sa.Column("summary_document_id", sa.UUID(), nullable=True),
        sa.Column("word_count", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column(
            "metadata",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("('{}'::jsonb)"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("project_id", "chapter_number", name="uq_chapter_project_number"),
    )
    op.create_index("idx_chapters_project_id", "chapters", ["project_id"], unique=False)
    op.create_index("idx_chapters_status", "chapters", ["status"], unique=False)
    op.create_table(
        "documents",
        sa.Column("id", sa.UUID(), server_default=sa.text("(gen_random_uuid())"), nullable=False),
        sa.Column("project_id", sa.UUID(), nullable=False),
        sa.Column("chapter_id", sa.UUID(), nullable=True),
        sa.Column("type", sa.Text(), nullable=False),
        sa.Column("title", sa.Text(), nullable=True),
        sa.Column("path", sa.Text(), nullable=False),
        sa.Column("current_version_id", sa.UUID(), nullable=True),
        sa.Column(
            "metadata",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("('{}'::jsonb)"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["chapter_id"], ["chapters.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["current_version_id"],
            ["document_versions.id"],
            name="fk_documents_current_version",
            ondelete="SET NULL",
            use_alter=True,
        ),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("project_id", "path", name="uq_document_project_path"),
    )
    op.create_index("idx_documents_chapter_id", "documents", ["chapter_id"], unique=False)
    op.create_index("idx_documents_path", "documents", ["path"], unique=False)
    op.create_index("idx_documents_project_id", "documents", ["project_id"], unique=False)
    op.create_index("idx_documents_type", "documents", ["type"], unique=False)
    op.create_table(
        "workflow_runs",
        sa.Column("id", sa.UUID(), server_default=sa.text("(gen_random_uuid())"), nullable=False),
        sa.Column("project_id", sa.UUID(), nullable=True),
        sa.Column("chapter_id", sa.UUID(), nullable=True),
        sa.Column("workflow_type", sa.Text(), nullable=False),
        sa.Column("status", sa.Text(), nullable=False),
        sa.Column("current_node", sa.Text(), nullable=True),
        sa.Column("next_node", sa.Text(), nullable=True),
        sa.Column("awaiting_user", sa.Boolean(), server_default=sa.text("(false)"), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=True),
        sa.Column(
            "started_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "metadata",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("('{}'::jsonb)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["chapter_id"], ["chapters.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_workflow_runs_awaiting_user", "workflow_runs", ["awaiting_user"], unique=False
    )
    op.create_index("idx_workflow_runs_chapter_id", "workflow_runs", ["chapter_id"], unique=False)
    op.create_index("idx_workflow_runs_project_id", "workflow_runs", ["project_id"], unique=False)
    op.create_index(
        "idx_workflow_runs_type_status", "workflow_runs", ["workflow_type", "status"], unique=False
    )
    op.create_table(
        "action_requests",
        sa.Column("id", sa.UUID(), server_default=sa.text("(gen_random_uuid())"), nullable=False),
        sa.Column("workflow_run_id", sa.UUID(), nullable=False),
        sa.Column("project_id", sa.UUID(), nullable=True),
        sa.Column("chapter_id", sa.UUID(), nullable=True),
        sa.Column("request_type", sa.Text(), nullable=False),
        sa.Column("status", sa.Text(), server_default=sa.text("'pending'"), nullable=False),
        sa.Column("prompt", sa.Text(), nullable=False),
        sa.Column(
            "options",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("('[]'::jsonb)"),
            nullable=False,
        ),
        sa.Column("default_option", sa.Text(), nullable=True),
        sa.Column("user_decision", sa.Text(), nullable=True),
        sa.Column("user_feedback", sa.Text(), nullable=True),
        sa.Column("resolved_by", sa.UUID(), nullable=True),
        sa.Column("resolved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "metadata",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("('{}'::jsonb)"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["chapter_id"], ["chapters.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["resolved_by"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["workflow_run_id"], ["workflow_runs.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_action_requests_project_chapter",
        "action_requests",
        ["project_id", "chapter_id"],
        unique=False,
    )
    op.create_index("idx_action_requests_status", "action_requests", ["status"], unique=False)
    op.create_index(
        "idx_action_requests_workflow_run_id", "action_requests", ["workflow_run_id"], unique=False
    )
    op.create_table(
        "agent_conversations",
        sa.Column("id", sa.UUID(), server_default=sa.text("(gen_random_uuid())"), nullable=False),
        sa.Column("project_id", sa.UUID(), nullable=False),
        sa.Column("chapter_id", sa.UUID(), nullable=True),
        sa.Column("workflow_run_id", sa.UUID(), nullable=True),
        sa.Column("agent_role", sa.Text(), nullable=False),
        sa.Column("title", sa.Text(), nullable=True),
        sa.Column("status", sa.Text(), server_default=sa.text("'active'"), nullable=False),
        sa.Column(
            "metadata",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("('{}'::jsonb)"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["chapter_id"], ["chapters.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["workflow_run_id"], ["workflow_runs.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_agent_conversations_chapter_id", "agent_conversations", ["chapter_id"], unique=False
    )
    op.create_index(
        "idx_agent_conversations_project_id", "agent_conversations", ["project_id"], unique=False
    )
    op.create_index(
        "idx_agent_conversations_role", "agent_conversations", ["agent_role"], unique=False
    )
    op.create_table(
        "document_versions",
        sa.Column("id", sa.UUID(), server_default=sa.text("(gen_random_uuid())"), nullable=False),
        sa.Column("document_id", sa.UUID(), nullable=False),
        sa.Column("version_number", sa.Integer(), nullable=False),
        sa.Column("parent_version_id", sa.UUID(), nullable=True),
        sa.Column("source", sa.Text(), nullable=False),
        sa.Column("actor_user_id", sa.UUID(), nullable=True),
        sa.Column("agent_role", sa.Text(), nullable=True),
        sa.Column("workflow_run_id", sa.UUID(), nullable=True),
        sa.Column("content_hash", sa.Text(), nullable=False),
        sa.Column("byte_size", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("word_count", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("file_path", sa.Text(), nullable=False),
        sa.Column("snapshot_path", sa.Text(), nullable=True),
        sa.Column("change_summary", sa.Text(), nullable=True),
        sa.Column(
            "metadata",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("('{}'::jsonb)"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["actor_user_id"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["document_id"], ["documents.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["parent_version_id"], ["document_versions.id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(["workflow_run_id"], ["workflow_runs.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("document_id", "version_number", name="uq_document_version_number"),
    )
    op.create_index(
        "idx_document_versions_document_id", "document_versions", ["document_id"], unique=False
    )
    op.create_index("idx_document_versions_source", "document_versions", ["source"], unique=False)
    op.create_index(
        "idx_document_versions_created_at",
        "document_versions",
        [sa.text("created_at DESC")],
        unique=False,
    )
    op.create_index(
        "idx_document_versions_workflow_run_id",
        "document_versions",
        ["workflow_run_id"],
        unique=False,
    )
    op.create_foreign_key(
        "fk_documents_current_version",
        "documents",
        "document_versions",
        ["current_version_id"],
        ["id"],
        ondelete="SET NULL",
    )
    op.create_table(
        "workflow_checkpoints",
        sa.Column("id", sa.UUID(), server_default=sa.text("(gen_random_uuid())"), nullable=False),
        sa.Column("workflow_run_id", sa.UUID(), nullable=False),
        sa.Column("checkpoint_index", sa.Integer(), nullable=False),
        sa.Column("node_name", sa.Text(), nullable=True),
        sa.Column("state_json", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["workflow_run_id"], ["workflow_runs.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "workflow_run_id", "checkpoint_index", name="uq_workflow_checkpoint_index"
        ),
    )
    op.create_index(
        "idx_workflow_checkpoints_run_id", "workflow_checkpoints", ["workflow_run_id"], unique=False
    )
    op.create_index(
        "idx_workflow_checkpoints_state_gin",
        "workflow_checkpoints",
        ["state_json"],
        unique=False,
        postgresql_using="gin",
    )
    op.create_table(
        "workflow_events",
        sa.Column("id", sa.UUID(), server_default=sa.text("(gen_random_uuid())"), nullable=False),
        sa.Column("workflow_run_id", sa.UUID(), nullable=False),
        sa.Column("event_type", sa.Text(), nullable=False),
        sa.Column("node_name", sa.Text(), nullable=True),
        sa.Column("actor_type", sa.Text(), server_default=sa.text("'system'"), nullable=False),
        sa.Column("actor_id", sa.Text(), nullable=True),
        sa.Column("message", sa.Text(), nullable=True),
        sa.Column(
            "payload",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("('{}'::jsonb)"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["workflow_run_id"], ["workflow_runs.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_workflow_events_run_id", "workflow_events", ["workflow_run_id"], unique=False
    )
    op.create_index("idx_workflow_events_type", "workflow_events", ["event_type"], unique=False)
    op.create_table(
        "agent_messages",
        sa.Column("id", sa.UUID(), server_default=sa.text("(gen_random_uuid())"), nullable=False),
        sa.Column("conversation_id", sa.UUID(), nullable=False),
        sa.Column("workflow_run_id", sa.UUID(), nullable=True),
        sa.Column("role", sa.Text(), nullable=False),
        sa.Column("agent_role", sa.Text(), nullable=True),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("structured_content", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("model_provider", sa.Text(), nullable=True),
        sa.Column("model_name", sa.Text(), nullable=True),
        sa.Column("prompt_tokens", sa.Integer(), nullable=True),
        sa.Column("completion_tokens", sa.Integer(), nullable=True),
        sa.Column("total_tokens", sa.Integer(), nullable=True),
        sa.Column("cost_usd", sa.Numeric(precision=12, scale=6), nullable=True),
        sa.Column(
            "metadata",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("('{}'::jsonb)"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["conversation_id"], ["agent_conversations.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["workflow_run_id"], ["workflow_runs.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_agent_messages_conversation_id", "agent_messages", ["conversation_id"], unique=False
    )
    op.create_index("idx_agent_messages_created_at", "agent_messages", ["created_at"], unique=False)
    op.create_index(
        "idx_agent_messages_structured_gin",
        "agent_messages",
        ["structured_content"],
        unique=False,
        postgresql_using="gin",
    )
    op.create_index(
        "idx_agent_messages_workflow_run_id", "agent_messages", ["workflow_run_id"], unique=False
    )
    op.create_table(
        "review_reports",
        sa.Column("id", sa.UUID(), server_default=sa.text("(gen_random_uuid())"), nullable=False),
        sa.Column("project_id", sa.UUID(), nullable=False),
        sa.Column("chapter_id", sa.UUID(), nullable=True),
        sa.Column("workflow_run_id", sa.UUID(), nullable=True),
        sa.Column("review_mode", sa.Text(), nullable=False),
        sa.Column("reviewer_agent_role", sa.Text(), nullable=False),
        sa.Column("target_document_id", sa.UUID(), nullable=True),
        sa.Column("target_version_id", sa.UUID(), nullable=True),
        sa.Column("passed", sa.Boolean(), server_default=sa.text("(false)"), nullable=False),
        sa.Column("summary", sa.Text(), nullable=False),
        sa.Column(
            "blocking_issues",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("('[]'::jsonb)"),
            nullable=False,
        ),
        sa.Column(
            "warnings",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("('[]'::jsonb)"),
            nullable=False,
        ),
        sa.Column(
            "notes",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("('[]'::jsonb)"),
            nullable=False,
        ),
        sa.Column(
            "suggested_actions",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("('[]'::jsonb)"),
            nullable=False,
        ),
        sa.Column(
            "raw_report",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("('{}'::jsonb)"),
            nullable=False,
        ),
        sa.Column("report_document_id", sa.UUID(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["chapter_id"], ["chapters.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["report_document_id"], ["documents.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["target_document_id"], ["documents.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(
            ["target_version_id"], ["document_versions.id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(["workflow_run_id"], ["workflow_runs.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_review_reports_blocking_gin",
        "review_reports",
        ["blocking_issues"],
        unique=False,
        postgresql_using="gin",
    )
    op.create_index("idx_review_reports_chapter_id", "review_reports", ["chapter_id"], unique=False)
    op.create_index("idx_review_reports_mode", "review_reports", ["review_mode"], unique=False)
    op.create_index("idx_review_reports_passed", "review_reports", ["passed"], unique=False)
    op.create_index("idx_review_reports_project_id", "review_reports", ["project_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    op.drop_table("review_reports")
    op.drop_table("agent_messages")
    op.drop_table("workflow_events")
    op.drop_table("workflow_checkpoints")
    op.drop_constraint("fk_documents_current_version", "documents", type_="foreignkey")
    op.drop_table("document_versions")
    op.drop_table("agent_conversations")
    op.drop_table("action_requests")
    op.drop_table("workflow_runs")
    op.drop_table("documents")
    op.drop_table("chapters")
    op.drop_table("projects")
    op.drop_table("users")
