"""Agent profiles, contracts, and narrow persistence boundaries."""

from app.agents.concept_agent import ConceptAgent, ConceptProvider
from app.agents.chief_editor import ChiefEditor, ChiefEditorProvider
from app.agents.composition import ProjectCreationComposition
from app.agents.contracts import (
    ConceptAgentRequest,
    ConceptGenerationOutput,
    ConceptOption,
    ChiefEditorReviewOutput,
    validate_concept_generation_output,
    validate_chief_editor_review_output,
)
from app.agents.errors import ConceptArtifactWorkflowError, ProfileRegistryError
from app.agents.maintenance_agents import (
    ChiefEditorAgent,
    ChiefEditorImpactAgent,
    ChiefEditorMaintenanceAgent,
    LoreAgent,
    MaintenanceImpactProvider,
    PlotArchitectAgent,
    RevisionPlanProvider,
    WorldbuildingAgent,
)
from app.agents.maintenance_contracts import (
    AffectedItemReference,
    AffectedItemType,
    ChiefEditorImpactOutput,
    ChiefEditorMaintenanceImpactOutput,
    DocumentVersionReference,
    ImpactAffectedItem,
    ImpactLevel,
    ImpactWarning,
    LoreImpactOutput,
    LoreMaintenanceImpactOutput,
    MaintenanceImpactOutput,
    MaintenanceImpactRequest,
    RevisionOperation,
    RevisionOperationKind,
    RevisionPlanOutput,
    RevisionPlanRequest,
    RevisionSafety,
    RevisionWarning,
    RewriteRequirement,
    WarningSeverity,
    validate_chief_editor_impact_output,
    validate_lore_impact_output,
    validate_revision_plan_output,
)
from app.agents.maintenance_fakes import (
    DeterministicMaintenanceProvider,
    canonical_json_bytes,
)
from app.agents.persistence import (
    persist_concept_generation_output,
    render_concept_options_markdown,
)
from app.agents.profiles import AgentProfile, ProfileRegistry

__all__ = [
    "AgentProfile",
    "AffectedItemReference",
    "AffectedItemType",
    "ChiefEditorImpactAgent",
    "ChiefEditorAgent",
    "ChiefEditorMaintenanceAgent",
    "ChiefEditorMaintenanceImpactOutput",
    "ChiefEditorImpactOutput",
    "ConceptAgent",
    "ConceptAgentRequest",
    "ConceptGenerationOutput",
    "ConceptOption",
    "ConceptProvider",
    "DeterministicMaintenanceProvider",
    "DocumentVersionReference",
    "ImpactAffectedItem",
    "ImpactLevel",
    "ChiefEditor",
    "ChiefEditorProvider",
    "ChiefEditorReviewOutput",
    "ImpactWarning",
    "LoreAgent",
    "LoreImpactOutput",
    "LoreMaintenanceImpactOutput",
    "MaintenanceImpactOutput",
    "MaintenanceImpactProvider",
    "MaintenanceImpactRequest",
    "PlotArchitectAgent",
    "ProjectCreationComposition",
    "ConceptArtifactWorkflowError",
    "ProfileRegistry",
    "ProfileRegistryError",
    "RevisionOperation",
    "RevisionOperationKind",
    "RevisionPlanOutput",
    "RevisionPlanProvider",
    "RevisionPlanRequest",
    "RevisionSafety",
    "RevisionWarning",
    "RewriteRequirement",
    "WarningSeverity",
    "WorldbuildingAgent",
    "canonical_json_bytes",
    "persist_concept_generation_output",
    "render_concept_options_markdown",
    "validate_concept_generation_output",
    "validate_chief_editor_review_output",
    "validate_chief_editor_impact_output",
    "validate_lore_impact_output",
    "validate_revision_plan_output",
]
